### ISSUE TITLE
Summarisation in different language.

### ISSUE THREAD

**Issue by MyraBaba** [pszemraj/textsum#10]
Hi,

thanks for sharing your work here to show us a path to follow .

I want to summarise Turk-ish meeting notes . We have some background knowledge NLD , tokenization etc. But very new to this AI era.

What would you recommend to us to follow ? Which model is suitable for this ?

Best

**Comment by pszemraj** [comment]
Hi 👋 thanks for your interest! I am not super experienced with Multi-lingual summarization, but it is a tricky field. Some recent progress in the field has been the multi-lingual pretraining/checkpoint of the equivalent of the base model used in this package (long-t5). The multilingual version is [mlong-t5](https://huggingface.co/agemagician/mlong-t5-tglobal-base). Also, it was pre-trained using some more recent techniques/advancements so it might even perform better than the English only one. There's a paper linked on the model card for more info. 

That said, you will need to fine-tune this model on some Turkish summarization dataset because the base checkpoint is a  very general starting point (itself a variety of tasks and languages). If you don't get to it before I do, I'll double check that it was pretrained with Turkish as one of the languages but IIRC it was like 20+ so I think it's in there


Hope that helps!

**Comment by pszemraj** [comment]
good news - Turkish is in the vocabulary/pretraining data, so fine-tuning the `mlong-T5` series of models on a Turkish-specific summarization dataset is what I'd recommend to start.

_(I'm going to close this as an issue for now - feel free to comment back here/re-open if needed, or [contact me](https://peterszemraj.ch/)_)


![mlongt5-xlsum](https://i.imgur.com/FgrOgGp.png)
