### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by TomLucidor** [pszemraj/textsum#14]
1. Can this work on whole books (especially those in PDF, EPUB, MOBI, or other ebook formats)?
2. How can "Chain of Density" (CoD) be implemented with this library for increased accuracy? [CoD Guide](https://www.prompthub.us/blog/better-summarization-with-chain-of-density-prompting)
3. Are there ways of handling both whole-book and chapter-by-chapter (or topic-by-topic) summaries so that it can have stronger coverage? [Optimal Approach with "Key Topics"](https://pashpashpash.substack.com/p/tackling-the-challenge-of-document)

Bonus read: https://github.com/gkamradt/langchain-tutorials/blob/main/data_generation/5%20Levels%20Of%20Summarization%20-%20Novice%20To%20Expert.ipynb

**Comment by pszemraj** [comment]
Hi! Thanks for reaching out. One thing you should note before going any further is that **this is a repo for text-to-text models and NOT text generation models**. Text-to-text models are trained to take an input and transform it to a given type of output, rather than being a swiss army knife for whatever the user asks. While there are [some exceptions](https://huggingface.co/bigscience/T0_3B), text-to-text models typically do "one thing" and don't "reason" etc like people expect text generation models to do. This repo is intended to provide a util for using text2text models trained to summarize text easily.

some answers to questions:

1. yes it can, but you need to convert any input to some text-like file beforehand. I had originally intended to include some PDF conversion (see basic demos [here](https://huggingface.co/spaces/pszemraj/pdf-ocr) and [here](https://huggingface.co/spaces/pszemraj/document-summarization)) but I decided this was beyond the scope of the package and wanted to keep things relatively clean and minimal.
    - this repo/code will summarize text of any length by breaking it down into batches of tokens and summarizing those. you can adjust this batch size from the default 4096 to be up to the model's max context length. You can see some examples of the params by looking at the [colab](https://colab.research.google.com/gist/pszemraj/ff8a8486dc3303199fe9c9790a606fff/textsum-summarize-text-files-example.ipynb) or [this page](https://github.com/pszemraj/textsum/wiki/Inference-&-Parameters)
    - since creating this package, there have been significantly improved methods for converting other files beyond my demos above such as those by Vik Paruchuri the creator of [Marker](https://github.com/VikParuchuri/marker). Give [his github page](https://github.com/VikParuchuri) a read, he's got multiple repos with varying levels of compute intensity to do this task. I would recommend using them as an initial step before you do any summarization with this repo or other models
2. I'll take a look at this more in detail, but my quick response is this is a technique for text generation models. Thus far and AFAIK, long-text text2text models as used in this repo **don't have prompting in their training**/it does nothing. Refer back to my initial point here
3. while it's not explicitly called this in this package, the batching I mention above in point 1) is essentially the "Map" of "Map-Reduce" as it's called in the article. You will get as output a list of summaries corresponding to the batches, and if you like you can use a text-generation model or another pass to aggregate those in a "Reduce" step.
    - I had some ideas for training a "reducer" model to aggregate the summaries (_see 'zero shot' version of this [here](https://huggingface.co/spaces/pszemraj/document-summarization/blob/main/aggregate.py)_), but the dataset doesnt exist and I havent had time to create one synthetically. but this would be an interesting pursuit and if created I'd be happy to include it in this repo. As you may find, using long-context text2text summarization models to "reduce" relatively short text summaries doesn't always work as well as you'd like. Depending on your use case, its sometimes fine to leave the outputs as-is

hope that helps for starters!

**Comment by TomLucidor** [comment]
Okay, in this case for No.2 I would like to see equivalents on things like "Chain of Density" for T2T models, since it is the structure of which they aggregate and re-process data that makes this interesting. Subtracting current summary output from the baseline text (math within embedding space maybe?), and then run another round to "squeeze" more summaries. Weird ideas

**Comment by pszemraj** [comment]
interesting idea, I'll let you know if make any progress on that. Some good news though, I've taken a pass at a model that can aggregate the summaries of text chunks into one, [more details on the model card here](https://huggingface.co/pszemraj/bart-large-summary-map-reduce)

will close this for now but if you have problems with anything feel free to reopen or create a new issue
